services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.next-app.rule=Host(`nisomnia.com`)
      - traefik.http.routers.next-app.entrypoints=websecure
      - traefik.http.routers.next-app.tls.certResolver=letsencrypt
      - traefik.http.services.next-app.loadbalancer.server.port=4321
    env_file:
      - .env
    restart: unless-stopped
