/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImageRouteImport } from './routes/image'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicIndexRouteImport } from './routes/topic/index'
import { Route as ArticleIndexRouteImport } from './routes/article/index'
import { Route as ArticleSlugRouteImport } from './routes/article/$slug'
import { Route as TopicSlugIndexRouteImport } from './routes/topic/$slug/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicIndexRoute = TopicIndexRouteImport.update({
  id: '/topic/',
  path: '/topic/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIndexRoute = ArticleIndexRouteImport.update({
  id: '/article/',
  path: '/article/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSlugIndexRoute = TopicSlugIndexRouteImport.update({
  id: '/topic/$slug/',
  path: '/topic/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/article/': typeof ArticleIndexRoute
  '/topic/': typeof TopicIndexRoute
  '/topic/$slug/': typeof TopicSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/article': typeof ArticleIndexRoute
  '/topic': typeof TopicIndexRoute
  '/topic/$slug': typeof TopicSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/article/': typeof ArticleIndexRoute
  '/topic/': typeof TopicIndexRoute
  '/topic/$slug/': typeof TopicSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image'
    | '/sitemap.xml'
    | '/article/$slug'
    | '/article/'
    | '/topic/'
    | '/topic/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image'
    | '/sitemap.xml'
    | '/article/$slug'
    | '/article'
    | '/topic'
    | '/topic/$slug'
  id:
    | '__root__'
    | '/'
    | '/image'
    | '/sitemap.xml'
    | '/article/$slug'
    | '/article/'
    | '/topic/'
    | '/topic/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageRoute: typeof ImageRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ArticleIndexRoute: typeof ArticleIndexRoute
  TopicIndexRoute: typeof TopicIndexRoute
  TopicSlugIndexRoute: typeof TopicSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/': {
      id: '/topic/'
      path: '/topic'
      fullPath: '/topic/'
      preLoaderRoute: typeof TopicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/': {
      id: '/article/'
      path: '/article'
      fullPath: '/article/'
      preLoaderRoute: typeof ArticleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$slug/': {
      id: '/topic/$slug/'
      path: '/topic/$slug'
      fullPath: '/topic/$slug/'
      preLoaderRoute: typeof TopicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageRoute: ImageRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ArticleIndexRoute: ArticleIndexRoute,
  TopicIndexRoute: TopicIndexRoute,
  TopicSlugIndexRoute: TopicSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
